[package]
name = "checkbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = { version = "*", features = ["serde"] }
dirs = "4"
regex = "1.7"
reqwest = { version = "*", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "*"
serde_repr = "*"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "*"

[dev-dependencies]
hyper = "*"
serde_derive = "1"

[profile.release]
opt-level = "s"
codegen-units = 1
lto = "thin"
strip = "debuginfo"
